Created diff eqs
CSCI-4314-Final-Project/rk4-solver pull request #3
Opened 2023-03-17 00:27 UTC by stefan-wass

2023-03-17 13:10 UTC, SidhantPuntambekar requested changes
It's interesting that all of these differential equations are multivariate so our Runge-Kutta solver should theoretically adapt to handle the variables of these equations. I'll need to make changes to the rk4 function to accommodate I think.

2023-03-17 13:10 UTC, SidhantPuntambekar commented on rk4_solver.py
> +    dE = s-(mu*E) + p*((E*T)/(h+T)) - (m*E*T) - (K_e*M*E)
shouldn't you add p(ET/h +t) before subtracting mu*E?

2023-03-19 20:41 UTC, SidhantPuntambekar commented
Also clean out all of the TODO items here

2023-03-21 23:18 UTC, SidhantPuntambekar commented on rk4_solver.py
> +    dE = s-(mu*E) + p*((E*T)/(h+T)) - (m*E*T) - (K_e*M*E)
Following discussion with Stefan, this equation is good. Lestari et al. are just bad at keeping their equations formatted correctly.

2023-03-21 23:19 UTC, SidhantPuntambekar approved these changes
Looks good to merge

2023-03-22 22:39 UTC, ssarthak01 commented
looks good to me

2023-03-22 22:39 UTC, ssarthak01 approved these changes
looks good!

2023-03-22 22:42 UTC, merged